# Generated by Django 3.2.7 on 2021-09-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitebackend', '0002_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='sitebackend.directiongroup'),
        ),
    ]
