# Generated by Django 3.2.7 on 2021-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebackend', '0003_alter_direction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
